routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
|--------------------------------------------------------------------------
| NOTA
|--------------------------------------------------------------------------
| Si no tienes usuarios ni roles de usuario en la base de datos, saca del
| grupo las rutas de roles y usuarios. Por si no quieres hacerlo con tinker
| o desde phpMyAdmin y accede a ellas con su url correspondiente.
|
| Roles: http://localhost:8000/roles
| Usuarios: Roles: http://localhost:8000/users
*/

/**
 * Solo tienen acceso usuarios autentificados.
 */
Route::group(['middleware' => 'auth'], function() {

    /**
     * Solo tienen acceso usuarios con rol de director.
     */
    Route::group(['middleware' => 'direc'], function() {

        // Roles de usuario.
        Route::resource('roles', 'RolController');

        // Usuarios.
        Route::resource('users', 'UserController');

        // Materias.
        Route::resource('materias', 'MateriaController');

        //Nivel Educativo
        Route::resource('nivel', 'NivelEducativoController');

        // Grados
        Route::resource('grados', 'GradoController');

        // Años
        Route::resource('anios','AnioController');

        // Valores
        Route::resource('valores','ValorController'); 
    });

    /**
     * Solo tienen acceso usuarios con rol de director o secretaria.
     */
    Route::group(['middleware' => 'direc'], function() {

        // Docentes.
        Route::resource('docentes', 'DocenteController');

        //Jornada laboral
        Route::resource('jornadas','JornadaController');

        // Pago de alimentos.
        Route::resource('pagos', 'PagoController');
        Route::post('pagos/{pago}/store', 'PagoController@store2')->name('pagos.store2');
        Route::delete('pagos/{pago}/destroy', 'PagoController@destroy2')->name('pagos.destroy2');

        Route::resource('recursos', 'RecursoController');
    });

    // Alumnos.
    Route::resource('alumnos','AlumnoController');

    // Récord de notas.
    Route::get('alumnos/{alumno}/record', 'AlumnoController@record')->name('alumnos.record');

    // Matriculas.
    Route::resource('matriculas','MatriculaController');

    // Notas.
    Route::get('notas', 'NotaController@index')->name('notas.index');
    Route::get('notas/{gra_mat}/edit', 'NotaController@edit')->name('notas.edit');
    Route::put('notas/update', 'NotaController@update')->name('notas.update');

    // Conducta.
    Route::get('notas/conducta/{grado}/edit', 'NotaController@editConducta')->name('conducta.edit');
    Route::put('notas/conducta/update', 'NotaController@updateConducta')->name('conducta.update');

    // Evaluaciones.
    Route::get('evaluaciones/{gra_mat}/create', 'EvaluacionController@create')->name('evaluaciones.create');
    Route::post('evaluaciones/store', 'EvaluacionController@store')->name('evaluaciones.store');
    Route::get('evaluaciones/{gra_mat}/{evaluacion}/subir', 'EvaluacionController@subir')->name('evaluaciones.subir');
    Route::get('evaluaciones/{gra_mat}/{evaluacion}/bajar', 'EvaluacionController@bajar')->name('evaluaciones.bajar');
    Route::get('evaluaciones/{evaluacion}/edit', 'EvaluacionController@edit')->name('evaluaciones.edit');
    Route::put('evaluaciones/{evaluacion}/update', 'EvaluacionController@update')->name('evaluaciones.update');
    Route::get('evaluaciones/{evaluacion}', 'EvaluacionController@destroy')->name('evaluaciones.destroy');

    // Reportes de notas.
    Route::get('notas/{grado}/reportes', 'NotaController@createReporte')->name('notas.create-reporte');
    Route::post('notas/reportes/descargar', 'NotaController@downloadReporte')->name('notas.reporte');

    // Vista de la Pagina Reportes
    Route::get('reportes', function(){
	    return view('pdf.principal');
    })->name('reportes');

    // Para descargar PDF de Grados
    Route::get('descargar/grados', 'GradoController@pdf')->name('grados.pdf');

    // Para descargar PDF de Docentes
    Route::get('descargar/docentes', 'DocenteController@pdf')->name('docentes.pdf');

    // Para descargar PDF de niveles
    Route::get('descargar/niveles', 'NivelEducativoController@pdf')->name('nivel.pdf');

    // Para descargar PDF de MAterias
    Route::get('descargar/materias', 'MateriaController@pdf')->name('materias.pdf');

    // Para descargar PDF de Jornadas Laborales
    Route::get('descargar/jornadas', 'JornadaController@pdf')->name('jornadas.pdf');

    // Editar imagen de perfil.
    Route::put('/{user}', 'HomeController@actualizarImagen')->name('actualizar-imagen');
    
    // Editar contraseña.
    Route::put('/{user}/password', 'HomeController@actualizarPassword')->name('actualizar-password');

});

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Nivel.php
<?php

namespace DSIproject;

use Illuminate\Database\Eloquent\Model;

class Nivel extends Model
{
    /**
     * Nombre de la tabla relacionada a este modelo.
     *
     * @var string
     */
    protected $table = 'niveles';

    /**
     * Atributos que son asignados en masa.
     *
     * @var array
     */
    protected $fillable = [
    	'codigo',
    	'nombre',
    	'orientador_materia',
    	'estado',
    ];

    /**
     * Obtiene los grados relacionados al nivel educativo.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function grados()
    {
        return $this->hasMany('DSIproject\Grado');
    }

    /**
     * Obtiene las materias que imparte el nivel educativo.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function materias()
    {
        return $this->belongsToMany('DSIproject\Materia')->withTimestamps();
    }
}

resources/views/nivel/create.blade.php
@extends('layouts.general')

@section('titulo', 'CEAA | Crear Nivel Educativo')

@section('estilos')
<!-- Select2 -->
<link rel="stylesheet" href="{{ asset('css/select2.min.css') }}">
@endsection

@section('encabezado', 'Crear Nivel Educativo')

@section('subencabezado', 'Registro')

@section('breadcrumb')
<li>
  <i class="fa fa-cog"></i> Configuración
</li>
<li>
  <a href="{{ route('nivel.index') }}">Nivel Educativo</a>
</li>
<li class="active">
  Registrar Nivel Educativo
</li>
@endsection

@section('contenido')
<!-- Box Primary -->
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Registrar Nivel Educativo</h3>
  </div>
  <!-- Formulario -->
  {!! Form::open(['route' => 'nivel.store', 'autocomplete' => 'off', 'method' => 'POST', 'class' => 'form-horizontal']) !!}
    <div class="box-body">
      <!-- Código -->
      <div class="form-group{{ $errors->has('codigo') ? ' has-error' : '' }}">
        {!! Form::label('Codigo', 'Código', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
          {!! Form::text('codigo', old('codigo'), ['class' => 'form-control', 'placeholder' => 'Código del Nivel Educativo', 'required']) !!}
            @if ($errors->has('codigo'))
            <span class="help-block">{{ $errors->first('codigo') }}</span>
            @endif
        </div>
      </div>
      <!-- Nombre -->
      <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
        {!! Form::label('nombre', 'Nombre', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
          {!! Form::text('nombre', old('nombre'), ['class' => 'form-control', 'placeholder' => 'Nombre del Nivel Educativo', 'required']) !!}
            @if ($errors->has('nombre'))
            <span class="help-block">{{ $errors->first('nombre') }}</span>
            @endif
        </div>
      </div>
      <!-- Materias -->
      <div class="form-group">
        {!! Form::label('materias', 'Materias', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
          {!! Form::select('materias[]', $materias, old('materias[]'), ['class' => 'form-control select2', 'multiple' => 'multiple', 'data-placeholder' => '-- Seleccione las materias que se imparten --', 'style' => 'width: 100%']) !!}
        </div>
      </div>
      <!-- Orientador imparte todas las materias -->
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-6">
          <div class="checkbox">
            <label>
              {!! Form::checkbox('orientador_materia', 1) !!} Orientador imparte todas las materias
            </label>
          </div>
        </div>
      </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
      <div class="col-sm-9">
        <div class="pull-right">
          <a href="{{ route('nivel.index') }}" class="btn btn-default btn-flat">Cancelar</a>
          {!! Form::submit('Guardar', ['class' => 'btn btn-primary btn-flat']) !!}
        </div>
      </div>
    </div>
  {!! Form::close() !!}
  <!-- /.box-footer-->
</div>
<!-- /.box -->
@endsection

@section('scripts')
<!-- Select2 -->
<script src="{{ asset('js/select2.full.min.js') }}"></script>
<script type="text/javascript">
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()
  })
</script>
@endsection

resources/views/nivel/edit.blade.php
@extends('layouts.general')

@section('titulo', 'CEAA | Nivel Educativo')

@section('estilos')
<!-- Select2 -->
<link rel="stylesheet" href="{{ asset('css/select2.min.css') }}">
@endsection

@section('encabezado', 'Nivel Educativo')

@section('subencabezado', 'Editar')

@section('breadcrumb')
<li>
  <i class="fa fa-cog"></i> Configuración
</li>
<li>
  <a href="{{ route('nivel.index') }}">Nivel Educativo</a>
</li>
<li class="active">
  Editar Nivel Educativo
</li>
@endsection

@section('contenido')
<!-- Box Primary -->
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Editar Nivel Educativo</h3>
  </div>
  <!-- Formulario -->
  {!! Form::open(['route' => ['nivel.update',$nivel], 'autocomplete' => 'off', 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
    <div class="box-body">
      <!-- Código -->
      <div class="form-group{{ $errors->has('codigo') ? ' has-error' : '' }}">
        {!! Form::label('Codigo', 'Codigo', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
          {!! Form::text('codigo', $nivel->codigo, ['class' => 'form-control', 'placeholder' => 'Codigo', 'required']) !!}
            @if ($errors->has('codigo'))
            <span class="help-block">{{ $errors->first('codigo') }}</span>
            @endif
        </div>
      </div>
      <!-- Nombre -->
      <div class="form-group{{ $errors->has('nip') ? ' has-error' : '' }}">
        {!! Form::label('nombre', 'Nombre', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
          {!! Form::text('nombre', $nivel->nombre, ['class' => 'form-control', 'placeholder' => 'Nombre de nivel', 'required']) !!}
            @if ($errors->has('nombre'))
            <span class="help-block">{{ $errors->first('nombre') }}</span>
            @endif
        </div>
      </div>
      <!-- Materias -->
      <div class="form-group">
        {!! Form::label('materias', 'Materias', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
          {!! Form::select('materias[]', $materias, $mis_materias, ['class' => 'form-control select2', 'multiple' => 'multiple', 'data-placeholder' => '-- Seleccione las materias que se imparten --', 'style' => 'width: 100%']) !!}
        </div>
      </div>
      <!-- Orientador imparte todas las materias -->
      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-6">
          <div class="checkbox">
            <label>
              {!! Form::checkbox('orientador_materia', 1, $nivel->orientador_materia) !!} Orientador imparte todas las materias
            </label>
          </div>
        </div>
      </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
      <div class="col-sm-9">
        <div class="pull-right">
          <a href="{{ route('nivel.index') }}" class="btn btn-default btn-flat">Cancelar</a>
          {!! Form::submit('Guardar', ['class' => 'btn btn-primary btn-flat']) !!}
        </div>
      </div>
    </div>
  {!! Form::close() !!}
  <!-- /.box-footer-->
</div>
<!-- /.box -->
@endsection

@section('scripts')
<!-- Select2 -->
<script src="{{ asset('js/select2.full.min.js') }}"></script>
<script type="text/javascript">
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()
  })
</script>
@endsection

resources/views/nivel/index.blade.php
@extends('layouts.general')

@section('titulo', 'CEAA | Nivel Educativo')

@section('encabezado', 'Nivel Educativo ')

@section('subencabezado', 'Gestión')

@section('breadcrumb')
<li>
  <i class="fa fa-cog"></i> Configuración
</li>
<li class="active">
  Nivel Educativo
</li>
@endsection

@section('contenido')
<!-- Box Primary -->
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Gestión de Nivel Educativo</h3>
  </div>
  <div class="box-body">
    <div class="row">
      <div class="col-sm-6">
        <a href="{{ route('nivel.create') }}" class="btn btn-primary btn-flat">Registrar Nivel Educativo</a>
      </div>
     <div class="col-sm-6">
        <!-- Barra de búsqueda -->
        @include('nivel.search')
      </div>
    </div>
    <!-- Listado de niveles educativos -->
    @if ($nivel->count() > 0)
    <div class="table-responsive">
      <table class="table table-hover table-striped table-bordered table-quitar-margen">
        <thead>
          <tr>
            <th>codigo</th>
            <th>nombre</th>
            <th>orientador_materia</th>
          </tr>
        </thead>
        <tbody>
          @foreach($nivel as $niveles)
          <tr>
            <td>{{ $niveles->codigo }}</td>
            <td>{{ $niveles->nombre }}</td>
            <td>{{ $niveles->orientador_materia }}</td>
            <td>
              <a href="{{ route('nivel.show', $niveles->id) }}" class="btn btn-default btn-flat">
                <i class="fa fa-eye" aria-hidden="true"></i>
              </a>
              <a href="{{ route('nivel.edit', $niveles->id) }}" class="btn btn-default btn-flat">
                <i class="fa fa-wrench" aria-hidden="true"></i>
              </a>
              <a href="" data-target="#modal-delete-{{ $niveles->id }}" data-toggle="modal" class="btn btn-danger btn-flat">
                <i class="fa fa-trash" aria-hidden="true"></i>
              </a>
            </td>
          </tr>
          <!-- Modal para dar de baja -->
          @include('nivel.modal')
          @endforeach
        </tbody>
      </table>
    </div>
    <!-- Si no hay docentes -->
    @else
      <div class="text-center">
        <i class="fa fa-search fa-5x" aria-hidden="true"></i>
        <h4>No se encontraron Nivel Educativo</h4>
      </div>
    @endif
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
    <div class="pull-right">
      <!-- Paginación -->
     {!! $nivel->render() !!}
    </div>
  </div>
  <!-- /.box-footer-->
</div>
<!-- /.box -->
@endsection

resources/views/nivel/modal.blade.php
<div class="modal fade modal-slide-in-right" aria-hidden="true" role="dialog" tabindex="-1" id="modal-delete-{{ $niveles->id }}">
  {!! Form::open(array('action' => array('NivelEducativoController@destroy', $niveles->id), 'method' => 'delete')) !!}
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">x</span>
          </button>
          <h4 class="modal-title">Baja de Nivel Educativo</h4>
        </div>
        <div class="modal-body">
          <p>¿Desea dar de baja al Nivel Educativo {{ $niveles->codigo }}?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary btn-flat">Aceptar</button>
        </div>
      </div>
    </div>
  {!! Form::close() !!}
</div>

resources/views/nivel/pdf.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Lista de Grados</title>
  <link rel="stylesheet" type="text/css" href="css/tabla.css">
</head>
<body>

<h2 align="center">
Centro Escolar Colegio a Reemplazar <br>
Codigo 12053 <br>
</h2>
<center>
<img src=" {{ asset('img/img.jpg')}} ">
</center>
<h3 align="center">Reporte de Docentes del centro escolar</h3>

<div class="table-responsive">
      <table class="table table-hover table-striped table-bordered table-quitar-margen">
       <thead>
          <tr>
            <th>codigo</th>
            <th>nombre</th>
            <th>orientador_materia</th>
          </tr>
        </thead>
        <tbody>
          @foreach($niveles as $nivel)
          <tr>
            <td>{{ $nivel->codigo }}</td>
            <td>{{ $nivel->nombre }}</td>
            <td>{{ $nivel->orientador_materia }}</td>
            </tr>
 @endforeach
</tbody>
</table>
</div>


</body>
</html>

resources/views/nivel/search.blade.php
{!! Form::open(array('url' => 'nivel', 'method' => 'GET', 'autocomplete' => 'off', 'nivel' => 'search')) !!}
  <div class="form-group">
    <div class="input-group">
      <input type="text" class="form-control" name="searchText", placeholder="Buscar", value="{{ $searchText }}"></input>
      <span class="input-group-btn">
        <button type="submit" class="btn btn-default">
          <i class="fa fa-search" aria-hidden="true"></i>
        </button>
      </span>
    </div>
  </div>
{!! Form::close() !!}

resources/views/nivel/show.blade.php
@extends('layouts.general')

@section('titulo', 'CEAA | Niveles Educativos')

@section('encabezado', 'Nivel Educativo')

@section('subencabezado', 'Detalle')

@section('breadcrumb')
<li>
  <i class="fa fa-cog"></i> Configuración
</li>
<li>
  <a href="{{ route('nivel.index') }}">Niveles Educativos</a>
</li>
<li class="active">
  Detalle del Nivel Educativo
</li>
@endsection

@section('contenido')
<!-- Box Primary -->
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">{{ $nivel->nombre }}</h3>
  </div>
  <div class="box-body">
    <div class="row">
      <div class="col-sm-6">
        <h4>Detalle</h4>
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-quitar-margen">
            <tr>
              <td><strong>Nombre:</strong> {{ $nivel->nombre }}</td>
            </tr>
            <tr>
              <td><strong>Código:</strong> {{ $nivel->codigo }}</td>
            </tr>
            @if ($nivel->orientador_materia == 1)
            <tr>
              <td><strong>Orientador imparte todas las materias</strong></td>
            </tr>
            @endif
            <tr>
              <td><strong>Registro:</strong> {{ \Carbon\Carbon::parse($nivel->created_at)->format('d/m/Y - H:i:s') }}</td>
            </tr>
            <tr>
              <td><strong>Última modificación:</strong> {{ \Carbon\Carbon::parse($nivel->updated_at)->format('d/m/Y - H:i:s') }}</td>
            </tr>
          </table>
        </div>
      </div>
      <div class="col-sm-6">
        <h4>Materias</h4>
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-quitar-margen">
            <thead>
              <tr>
                <th>Código</th>
                <th>Nombre</th>
              </tr>
            </thead>
            <tbody>
              @foreach($nivel->materias as $materia)
              <tr>
                <td>{{ $materia->codigo }}</td>
                <td>{{ $materia->nombre }}</td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
  </div>
  <!-- /.box-footer-->
</div>
<!-- /.box -->
@endsection