routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
|--------------------------------------------------------------------------
| NOTA
|--------------------------------------------------------------------------
| Si no tienes usuarios ni roles de usuario en la base de datos, saca del
| grupo las rutas de roles y usuarios. Por si no quieres hacerlo con tinker
| o desde phpMyAdmin y accede a ellas con su url correspondiente.
|
| Roles: http://localhost:8000/roles
| Usuarios: Roles: http://localhost:8000/users
*/

/**
 * Solo tienen acceso usuarios autentificados.
 */
Route::group(['middleware' => 'auth'], function() {

    /**
     * Solo tienen acceso usuarios con rol de director.
     */
    Route::group(['middleware' => 'direc'], function() {

        // Roles de usuario.
        Route::resource('roles', 'RolController');

        // Usuarios.
        Route::resource('users', 'UserController');

        // Materias.
        Route::resource('materias', 'MateriaController');

        //Nivel Educativo
        Route::resource('nivel', 'NivelEducativoController');

        // Grados
        Route::resource('grados', 'GradoController');

        // Años
        Route::resource('anios','AnioController');

        // Valores
        Route::resource('valores','ValorController'); 
    });

    /**
     * Solo tienen acceso usuarios con rol de director o secretaria.
     */
    Route::group(['middleware' => 'direc'], function() {

        // Docentes.
        Route::resource('docentes', 'DocenteController');

        //Jornada laboral
        Route::resource('jornadas','JornadaController');

        // Pago de alimentos.
        Route::resource('pagos', 'PagoController');
        Route::post('pagos/{pago}/store', 'PagoController@store2')->name('pagos.store2');
        Route::delete('pagos/{pago}/destroy', 'PagoController@destroy2')->name('pagos.destroy2');

        Route::resource('recursos', 'RecursoController');
    });

    // Alumnos.
    Route::resource('alumnos','AlumnoController');

    // Récord de notas.
    Route::get('alumnos/{alumno}/record', 'AlumnoController@record')->name('alumnos.record');

    // Matriculas.
    Route::resource('matriculas','MatriculaController');

    // Notas.
    Route::get('notas', 'NotaController@index')->name('notas.index');
    Route::get('notas/{gra_mat}/edit', 'NotaController@edit')->name('notas.edit');
    Route::put('notas/update', 'NotaController@update')->name('notas.update');

    // Conducta.
    Route::get('notas/conducta/{grado}/edit', 'NotaController@editConducta')->name('conducta.edit');
    Route::put('notas/conducta/update', 'NotaController@updateConducta')->name('conducta.update');

    // Evaluaciones.
    Route::get('evaluaciones/{gra_mat}/create', 'EvaluacionController@create')->name('evaluaciones.create');
    Route::post('evaluaciones/store', 'EvaluacionController@store')->name('evaluaciones.store');
    Route::get('evaluaciones/{gra_mat}/{evaluacion}/subir', 'EvaluacionController@subir')->name('evaluaciones.subir');
    Route::get('evaluaciones/{gra_mat}/{evaluacion}/bajar', 'EvaluacionController@bajar')->name('evaluaciones.bajar');
    Route::get('evaluaciones/{evaluacion}/edit', 'EvaluacionController@edit')->name('evaluaciones.edit');
    Route::put('evaluaciones/{evaluacion}/update', 'EvaluacionController@update')->name('evaluaciones.update');
    Route::get('evaluaciones/{evaluacion}', 'EvaluacionController@destroy')->name('evaluaciones.destroy');

    // Reportes de notas.
    Route::get('notas/{grado}/reportes', 'NotaController@createReporte')->name('notas.create-reporte');
    Route::post('notas/reportes/descargar', 'NotaController@downloadReporte')->name('notas.reporte');

    // Vista de la Pagina Reportes
    Route::get('reportes', function(){
	    return view('pdf.principal');
    })->name('reportes');

    // Para descargar PDF de Grados
    Route::get('descargar/grados', 'GradoController@pdf')->name('grados.pdf');

    // Para descargar PDF de Docentes
    Route::get('descargar/docentes', 'DocenteController@pdf')->name('docentes.pdf');

    // Para descargar PDF de niveles
    Route::get('descargar/niveles', 'NivelEducativoController@pdf')->name('nivel.pdf');

    // Para descargar PDF de MAterias
    Route::get('descargar/materias', 'MateriaController@pdf')->name('materias.pdf');

    // Para descargar PDF de Jornadas Laborales
    Route::get('descargar/jornadas', 'JornadaController@pdf')->name('jornadas.pdf');

    // Editar imagen de perfil.
    Route::put('/{user}', 'HomeController@actualizarImagen')->name('actualizar-imagen');
    
    // Editar contraseña.
    Route::put('/{user}/password', 'HomeController@actualizarPassword')->name('actualizar-password');

});

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/roles/create.blade.php
@extends('layouts.general')

@section('titulo', 'CEAA | Roles de usuario')

@section('encabezado', 'Roles de usuario')

@section('subencabezado', 'Registro')

@section('breadcrumb')
<li>
  <i class="fa fa-shield"></i> Seguridad
</li>
<li>
  <a href="{{ route('roles.index') }}">Roles de usuario</a>
</li>
<li class="active">
  Registrar Rol de Usuario
</li>
@endsection

@section('contenido')
<!-- Box Primary -->
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Registrar Rol de Usuario</h3>
  </div>
  <!-- Formulario -->
  {!! Form::open(['route' => 'roles.store', 'autocomplete' => 'off', 'method' => 'POST', 'class' => 'form-horizontal']) !!}
    <div class="box-body">
      <!-- Código -->
      <div class="form-group{{ $errors->has('codigo') ? ' has-error' : '' }}">
        {!! Form::label('codigo', 'Código', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
          {!! Form::text('codigo', old('codigo'), ['class' => 'form-control', 'placeholder' => 'Código del rol de usuario', 'required']) !!}
            @if ($errors->has('codigo'))
            <span class="help-block">{{ $errors->first('codigo') }}</span>
            @endif
        </div>
      </div>
      <!-- Nombre -->
      <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
        {!! Form::label('nombre', 'Nombre', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
          {!! Form::text('nombre', old('nombre'), ['class' => 'form-control', 'placeholder' => 'Nombre del rol de usuario', 'required']) !!}
            @if ($errors->has('nombre'))
            <span class="help-block">{{ $errors->first('nombre') }}</span>
            @endif
        </div>
      </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
      <div class="col-sm-9">
        <div class="pull-right">
          <a href="{{ route('roles.index') }}" class="btn btn-default btn-flat">Cancelar</a>
          {!! Form::submit('Guardar', ['class' => 'btn btn-primary btn-flat']) !!}
        </div>
      </div>
    </div>
  {!! Form::close() !!}
  <!-- /.box-footer-->
</div>
<!-- /.box -->
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.general')

@section('titulo', 'CEAA | Roles de usuario')

@section('encabezado', 'Roles de usuario')

@section('subencabezado', 'Edición')

@section('breadcrumb')
<li>
  <i class="fa fa-shield"></i> Seguridad
</li>
<li>
  <a href="{{ route('roles.index') }}">Roles de usuario</a>
</li>
<li class="active">
  Editar Rol de Usuario
</li>
@endsection

@section('contenido')
<!-- Box Primary -->
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Editar Rol de Usuario</h3>
  </div>
  <!-- Formulario -->
  {!! Form::open(['route' => ['roles.update', $rol], 'autocomplete' => 'off', 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
    <div class="box-body">
      <!-- Nombre -->
      <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
        {!! Form::label('nombre', 'Nombre', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-6">
          {!! Form::text('nombre', $rol->nombre, ['class' => 'form-control', 'placeholder' => 'Nombre del rol de usuario', 'required']) !!}
            @if ($errors->has('nombre'))
            <span class="help-block">{{ $errors->first('nombre') }}</span>
            @endif
        </div>
      </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
      <div class="col-sm-9">
        <div class="pull-right">
          <a href="{{ route('roles.index') }}" class="btn btn-default btn-flat">Cancelar</a>
          {!! Form::submit('Guardar', ['class' => 'btn btn-primary btn-flat']) !!}
        </div>
      </div>
    </div>
  {!! Form::close() !!}
  <!-- /.box-footer-->
</div>
<!-- /.box -->
@endsection

resources/views/roles/index.blade.php
@extends('layouts.general')

@section('titulo', 'CEAA | Roles de usuario')

@section('encabezado', 'Roles de usuario')

@section('subencabezado', 'Gestión')

@section('breadcrumb')
<li>
  <i class="fa fa-shield"></i> Seguridad
</li>
<li class="active">
  Roles de usuario
</li>
@endsection

@section('contenido')
<!-- Box Primary -->
<div class="box box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Gestión de Roles de Usuario</h3>
  </div>
  <div class="box-body">
    <div class="row">
      <div class="col-sm-6">
        <a href="{{ route('roles.create') }}" class="btn btn-primary btn-flat">Registrar rol de usuario</a>
      </div>
      <div class="col-sm-6">
      	<!-- Barra de búsqueda -->
      	@include('roles.search')
      </div>
    </div>
  	<!-- Listado de roles de usuario -->
  	@if ($roles->count() > 0)
  	<div class="table-responsive">
      <table class="table table-hover table-striped table-bordered table-quitar-margen">
        <thead>
          <tr>
            <th>ID</th>
            <th>Código</th>
            <th>Nombre</th>
            <th>Opciones</th>
          </tr>
        </thead>
        <tbody>
          @foreach($roles as $rol)
          <tr>
            <td>{{ $rol->id }}</td>
            <td>{{ $rol->codigo }}</td>
            <td>{{ $rol->nombre }}</td>
            <td>
              <a href="{{ route('roles.edit', $rol->id) }}" class="btn btn-default btn-flat">
                <i class="fa fa-wrench" aria-hidden="true"></i>
              </a>
              <a href="" data-target="#modal-delete-{{ $rol->id }}" data-toggle="modal" class="btn btn-danger btn-flat">
                <i class="fa fa-trash" aria-hidden="true"></i>
              </a>
            </td>
          </tr>
          <!-- Modal para dar de baja -->
          @include('roles.modal')
          @endforeach
        </tbody>
      </table>
    </div>
    <!-- Si no hay roles de usuario -->
    @else
      <div class="text-center">
        <i class="fa fa-search fa-5x" aria-hidden="true"></i>
        <h4>No se encontraron roles de usuario</h4>
      </div>
    @endif
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
    <div class="pull-right">
    	<!-- Paginación -->
      {!! $roles->render() !!}
    </div>
  </div>
  <!-- /.box-footer-->
</div>
<!-- /.box -->
@endsection

resources/views/roles/modal.blade.php
<div class="modal fade modal-slide-in-right" aria-hidden="true" role="dialog" tabindex="-1" id="modal-delete-{{ $rol->id }}">
  {!! Form::open(array('action' => array('RolController@destroy', $rol->id), 'method' => 'delete')) !!}
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">x</span>
          </button>
          <h4 class="modal-title">Baja de Rol de Usuario</h4>
        </div>
        <div class="modal-body">
          <p>¿Desea dar de baja al rol de usuario {{ $rol->nombre }}?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary btn-flat">Aceptar</button>
        </div>
      </div>
    </div>
  {!! Form::close() !!}
</div>

resources/views/roles/search.blade.php
{!! Form::open(array('url' => 'roles', 'method' => 'GET', 'autocomplete' => 'off', 'role' => 'search')) !!}
  <div class="form-group">
    <div class="input-group">
      <input type="text" class="form-control" name="searchText", placeholder="Buscar", value="{{ $searchText }}"></input>
      <span class="input-group-btn">
        <button type="submit" class="btn btn-default">
          <i class="fa fa-search" aria-hidden="true"></i>
        </button>
      </span>
    </div>
  </div>
{!! Form::close() !!}